import type { ReEngagementRule, ReEngagementLog } from '@/types/sales';

export const reEngagementRules: ReEngagementRule[] = [
  {
    id: 'rer_1',
    name: 'Cold Lead — WhatsApp Re-engage',
    trigger: 'lead_cold',
    triggerLabel: 'Lead goes cold (3+ days no contact)',
    conditions: { daysSinceContact: 3, temperature: 'cold' },
    actions: [
      { type: 'send_wa_template', label: 'Send "we_miss_you" WA template', templateName: 'we_miss_you', delay: 0, delayUnit: 'minutes' },
      { type: 'schedule_call', label: 'Schedule follow-up call in 24h', delay: 24, delayUnit: 'hours' },
    ],
    enabled: true,
    totalTriggered: 47,
    successRate: 34,
    lastTriggered: '2024-12-14T08:00:00Z',
    createdAt: '2024-11-01',
  },
  {
    id: 'rer_2',
    name: 'No Response 5 Days — Escalate',
    trigger: 'no_response_5d',
    triggerLabel: 'No response for 5+ days',
    conditions: { daysSinceContact: 5 },
    actions: [
      { type: 'send_wa_template', label: 'Send "last_chance" WA template', templateName: 'last_chance', delay: 0, delayUnit: 'minutes' },
      { type: 'send_email', label: 'Send re-engagement email', delay: 2, delayUnit: 'hours' },
      { type: 'assign_to_senior', label: 'Assign to senior consultant', delay: 24, delayUnit: 'hours' },
    ],
    enabled: true,
    totalTriggered: 23,
    successRate: 22,
    lastTriggered: '2024-12-14T07:00:00Z',
    createdAt: '2024-11-05',
  },
  {
    id: 'rer_3',
    name: 'No-Show — Auto Rebook',
    trigger: 'noshow',
    triggerLabel: 'Lead is a no-show on discovery call',
    conditions: {},
    actions: [
      { type: 'send_wa_template', label: 'Send "missed_call_rebook" WA template', templateName: 'missed_call_rebook', delay: 30, delayUnit: 'minutes' },
      { type: 'schedule_call', label: 'Auto-schedule new call in 48h', delay: 48, delayUnit: 'hours' },
    ],
    enabled: true,
    totalTriggered: 12,
    successRate: 58,
    lastTriggered: '2024-12-12T09:30:00Z',
    createdAt: '2024-11-10',
  },
  {
    id: 'rer_4',
    name: 'Proposal Not Opened — Nudge',
    trigger: 'proposal_not_opened',
    triggerLabel: 'Proposal not opened within 48 hours',
    conditions: {},
    actions: [
      { type: 'send_wa_template', label: 'Send "proposal_reminder" WA template', templateName: 'proposal_reminder', delay: 0, delayUnit: 'minutes' },
    ],
    enabled: true,
    totalTriggered: 18,
    successRate: 72,
    lastTriggered: '2024-12-13T22:00:00Z',
    createdAt: '2024-11-12',
  },
  {
    id: 'rer_5',
    name: 'Stage Stuck 7 Days — Intervene',
    trigger: 'stage_stuck',
    triggerLabel: 'Lead stuck in same stage for 7+ days',
    conditions: { daysSinceContact: 7, minScore: 30 },
    actions: [
      { type: 'send_wa_template', label: 'Send "check_in" WA template', templateName: 'check_in', delay: 0, delayUnit: 'minutes' },
      { type: 'schedule_call', label: 'Book personal call', delay: 4, delayUnit: 'hours' },
      { type: 'assign_to_senior', label: 'Flag for manager review', delay: 24, delayUnit: 'hours' },
    ],
    enabled: false,
    totalTriggered: 8,
    successRate: 38,
    lastTriggered: '2024-12-10T14:00:00Z',
    createdAt: '2024-11-20',
  },
  {
    id: 'rer_6',
    name: 'SLA Breach — Immediate Action',
    trigger: 'sla_breach',
    triggerLabel: 'First response SLA breached (>2 hrs)',
    conditions: {},
    actions: [
      { type: 'send_wa_template', label: 'Send "quick_hello" WA template', templateName: 'quick_hello', delay: 0, delayUnit: 'minutes' },
      { type: 'assign_to_senior', label: 'Alert team lead', delay: 0, delayUnit: 'minutes' },
    ],
    enabled: true,
    totalTriggered: 31,
    successRate: 65,
    lastTriggered: '2024-12-14T06:15:00Z',
    createdAt: '2024-11-02',
  },
];

export const reEngagementLogs: ReEngagementLog[] = [
  { id: 'rel_1', ruleId: 'rer_1', ruleName: 'Cold Lead — WhatsApp Re-engage', leadId: 'l5', leadName: 'Suresh Reddy', trigger: 'lead_cold', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "we_miss_you" WA', status: 'success' }, { type: 'schedule_call', label: 'Schedule call', status: 'pending' }], outcome: 'no_response', triggeredAt: '2024-12-14T08:00:00Z' },
  { id: 'rel_2', ruleId: 'rer_1', ruleName: 'Cold Lead — WhatsApp Re-engage', leadId: 'l10', leadName: 'Neha Gupta', trigger: 'lead_cold', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "we_miss_you" WA', status: 'success' }, { type: 'schedule_call', label: 'Schedule call', status: 'success' }], outcome: 'responded', triggeredAt: '2024-12-14T07:00:00Z' },
  { id: 'rel_3', ruleId: 'rer_6', ruleName: 'SLA Breach — Immediate Action', leadId: 'l3', leadName: 'Rajesh Kumar', trigger: 'sla_breach', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "quick_hello" WA', status: 'success' }, { type: 'assign_to_senior', label: 'Alert team lead', status: 'success' }], outcome: 'responded', triggeredAt: '2024-12-14T06:15:00Z' },
  { id: 'rel_4', ruleId: 'rer_3', ruleName: 'No-Show — Auto Rebook', leadId: 'l8', leadName: 'Divya Menon', trigger: 'noshow', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "missed_call_rebook" WA', status: 'success' }, { type: 'schedule_call', label: 'Auto-schedule call', status: 'success' }], outcome: 'converted', triggeredAt: '2024-12-12T09:30:00Z' },
  { id: 'rel_5', ruleId: 'rer_4', ruleName: 'Proposal Not Opened — Nudge', leadId: 'l15', leadName: 'Deepak Choudhary', trigger: 'proposal_not_opened', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "proposal_reminder" WA', status: 'success' }], outcome: 'responded', triggeredAt: '2024-12-13T22:00:00Z' },
  { id: 'rel_6', ruleId: 'rer_2', ruleName: 'No Response 5 Days — Escalate', leadId: 'l16', leadName: 'Ritu Saxena', trigger: 'no_response_5d', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "last_chance" WA', status: 'success' }, { type: 'send_email', label: 'Send email', status: 'failed' }, { type: 'assign_to_senior', label: 'Assign senior', status: 'pending' }], outcome: 'no_response', triggeredAt: '2024-12-13T16:00:00Z' },
  { id: 'rel_7', ruleId: 'rer_5', ruleName: 'Stage Stuck 7 Days — Intervene', leadId: 'l18', leadName: 'Swati Kapoor', trigger: 'stage_stuck', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "check_in" WA', status: 'success' }, { type: 'schedule_call', label: 'Book call', status: 'success' }, { type: 'assign_to_senior', label: 'Flag manager', status: 'success' }], outcome: 'responded', triggeredAt: '2024-12-10T14:00:00Z' },
  { id: 'rel_8', ruleId: 'rer_1', ruleName: 'Cold Lead — WhatsApp Re-engage', leadId: 'l18', leadName: 'Swati Kapoor', trigger: 'lead_cold', actionsExecuted: [{ type: 'send_wa_template', label: 'Send "we_miss_you" WA', status: 'success' }, { type: 'schedule_call', label: 'Schedule call', status: 'failed' }], outcome: 'no_response', triggeredAt: '2024-12-11T10:00:00Z' },
];
