export const automationLogsSeed = [
  {
    _id: 'al1',
    leadId: 'l3',
    leadName: 'Rajesh Kumar',
    sequenceName: 'Not Ready — Gap nurture',
    step: 3,
    channel: 'WhatsApp' as const,
    status: 'Sent' as const,
    sentAt: new Date('2024-12-14T06:30:00Z'),
    openedAt: null,
  },
  {
    _id: 'al2',
    leadId: 'l1',
    leadName: 'Vikram Singh',
    sequenceName: 'Franchise Ready — Discovery push',
    step: 2,
    channel: 'Email' as const,
    status: 'Opened' as const,
    sentAt: new Date('2024-12-13T10:00:00Z'),
    openedAt: new Date('2024-12-13T14:00:00Z'),
  },
  {
    _id: 'al3',
    leadId: 'l6',
    leadName: 'Kavita Nair',
    sequenceName: 'Recruitment Only — Eden routing',
    step: 1,
    channel: 'WhatsApp' as const,
    status: 'Sent' as const,
    sentAt: new Date('2024-12-14T03:00:00Z'),
    openedAt: null,
  },
  {
    _id: 'al4',
    leadId: 'l18',
    leadName: 'Swati Kapoor',
    sequenceName: 'Not Ready — Gap nurture',
    step: 5,
    channel: 'WhatsApp' as const,
    status: 'Pending' as const,
    sentAt: new Date('2024-12-15T08:00:00Z'),
    openedAt: null,
  },
  {
    _id: 'al5',
    leadId: 'l2',
    leadName: 'Anita Desai',
    sequenceName: 'Post-proposal follow-up',
    step: 1,
    channel: 'WhatsApp' as const,
    status: 'Sent' as const,
    sentAt: new Date('2024-12-14T08:00:00Z'),
    openedAt: null,
  },
  {
    _id: 'al6',
    leadId: 'l10',
    leadName: 'Neha Gupta',
    sequenceName: 'Not Ready — Gap nurture',
    step: 6,
    channel: 'Voice' as const,
    status: 'Failed' as const,
    sentAt: new Date('2024-12-13T09:00:00Z'),
    openedAt: null,
  },
];
