export const automationSequencesSeed = [
  {
    _id: 's1',
    name: 'Not Ready — Gap nurture',
    track: 'Not Ready',
    steps: [
      {
        id: 'st1',
        stepNumber: 1,
        delay: 0,
        delayUnit: 'hours' as const,
        channel: 'WhatsApp' as const,
        template: 'gap_nurture_intro',
      },
      {
        id: 'st2',
        stepNumber: 2,
        delay: 2,
        delayUnit: 'days' as const,
        channel: 'Email' as const,
        template: 'gap_nurture_resources',
      },
      {
        id: 'st3',
        stepNumber: 3,
        delay: 5,
        delayUnit: 'days' as const,
        channel: 'WhatsApp' as const,
        template: 'gap_nurture_checkin',
      },
      {
        id: 'st4',
        stepNumber: 4,
        delay: 10,
        delayUnit: 'days' as const,
        channel: 'Email' as const,
        template: 'gap_nurture_content',
      },
      {
        id: 'st5',
        stepNumber: 5,
        delay: 15,
        delayUnit: 'days' as const,
        channel: 'WhatsApp' as const,
        template: 'gap_nurture_offer',
      },
      {
        id: 'st6',
        stepNumber: 6,
        delay: 18,
        delayUnit: 'days' as const,
        channel: 'Voice' as const,
        template: 'gap_nurture_call',
      },
      {
        id: 'st7',
        stepNumber: 7,
        delay: 20,
        delayUnit: 'days' as const,
        channel: 'WhatsApp' as const,
        template: 'gap_nurture_final',
      },
    ],
    activeLeads: 23,
    lastTriggered: new Date('2024-12-14T08:00:00Z'),
  },
  {
    _id: 's2',
    name: 'Franchise Ready — Discovery push',
    track: 'Franchise Ready',
    steps: [
      {
        id: 'st8',
        stepNumber: 1,
        delay: 0,
        delayUnit: 'hours' as const,
        channel: 'WhatsApp' as const,
        template: 'discovery_intro',
      },
      {
        id: 'st9',
        stepNumber: 2,
        delay: 1,
        delayUnit: 'days' as const,
        channel: 'Email' as const,
        template: 'discovery_benefits',
      },
      {
        id: 'st10',
        stepNumber: 3,
        delay: 3,
        delayUnit: 'days' as const,
        channel: 'WhatsApp' as const,
        template: 'discovery_book_cta',
      },
      {
        id: 'st11',
        stepNumber: 4,
        delay: 5,
        delayUnit: 'days' as const,
        channel: 'Voice' as const,
        template: 'discovery_call_attempt',
      },
    ],
    activeLeads: 15,
    lastTriggered: new Date('2024-12-14T07:30:00Z'),
  },
  {
    _id: 's3',
    name: 'Recruitment Only — Eden routing',
    track: 'Recruitment Only',
    steps: [
      {
        id: 'st12',
        stepNumber: 1,
        delay: 0,
        delayUnit: 'hours' as const,
        channel: 'WhatsApp' as const,
        template: 'eden_routing_intro',
      },
      {
        id: 'st13',
        stepNumber: 2,
        delay: 1,
        delayUnit: 'days' as const,
        channel: 'Email' as const,
        template: 'eden_details',
      },
    ],
    activeLeads: 5,
    lastTriggered: new Date('2024-12-13T14:00:00Z'),
  },
  {
    _id: 's4',
    name: 'Post-proposal follow-up',
    track: 'Franchise Ready',
    steps: [
      {
        id: 'st14',
        stepNumber: 1,
        delay: 1,
        delayUnit: 'days' as const,
        channel: 'WhatsApp' as const,
        template: 'proposal_followup_1',
      },
      {
        id: 'st15',
        stepNumber: 2,
        delay: 3,
        delayUnit: 'days' as const,
        channel: 'Email' as const,
        template: 'proposal_followup_2',
      },
      {
        id: 'st16',
        stepNumber: 3,
        delay: 5,
        delayUnit: 'days' as const,
        channel: 'Voice' as const,
        template: 'proposal_followup_call',
      },
    ],
    activeLeads: 8,
    lastTriggered: new Date('2024-12-14T06:00:00Z'),
  },
  {
    _id: 's5',
    name: 'No-response voice trigger',
    track: 'Franchise Ready',
    steps: [
      {
        id: 'st17',
        stepNumber: 1,
        delay: 7,
        delayUnit: 'days' as const,
        channel: 'Voice' as const,
        template: 'noresponse_voice',
      },
      {
        id: 'st18',
        stepNumber: 2,
        delay: 10,
        delayUnit: 'days' as const,
        channel: 'WhatsApp' as const,
        template: 'noresponse_final_wa',
      },
    ],
    activeLeads: 3,
    lastTriggered: new Date('2024-12-12T10:00:00Z'),
  },
];
