export const reEngagementLogsSeed = [
  {
    _id: 'rel_1',
    ruleId: 'rer_1',
    ruleName: 'Cold Lead — WhatsApp Re-engage',
    leadId: 'l5',
    leadName: 'Suresh Reddy',
    trigger: 'lead_cold',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "we_miss_you" WA',
        status: 'success',
      },
      { type: 'schedule_call', label: 'Schedule call', status: 'pending' },
    ],
    outcome: 'no_response',
    triggeredAt: new Date('2024-12-14T08:00:00Z'),
  },
  {
    _id: 'rel_2',
    ruleId: 'rer_1',
    ruleName: 'Cold Lead — WhatsApp Re-engage',
    leadId: 'l10',
    leadName: 'Neha Gupta',
    trigger: 'lead_cold',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "we_miss_you" WA',
        status: 'success',
      },
      { type: 'schedule_call', label: 'Schedule call', status: 'success' },
    ],
    outcome: 'responded',
    triggeredAt: new Date('2024-12-14T07:00:00Z'),
  },
  {
    _id: 'rel_3',
    ruleId: 'rer_6',
    ruleName: 'SLA Breach — Immediate Action',
    leadId: 'l3',
    leadName: 'Rajesh Kumar',
    trigger: 'sla_breach',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "quick_hello" WA',
        status: 'success',
      },
      { type: 'assign_to_senior', label: 'Alert team lead', status: 'success' },
    ],
    outcome: 'responded',
    triggeredAt: new Date('2024-12-14T06:15:00Z'),
  },
  {
    _id: 'rel_4',
    ruleId: 'rer_3',
    ruleName: 'No-Show — Auto Rebook',
    leadId: 'l8',
    leadName: 'Divya Menon',
    trigger: 'noshow',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "missed_call_rebook" WA',
        status: 'success',
      },
      { type: 'schedule_call', label: 'Auto-schedule call', status: 'success' },
    ],
    outcome: 'converted',
    triggeredAt: new Date('2024-12-12T09:30:00Z'),
  },
  {
    _id: 'rel_5',
    ruleId: 'rer_4',
    ruleName: 'Proposal Not Opened — Nudge',
    leadId: 'l15',
    leadName: 'Deepak Choudhary',
    trigger: 'proposal_not_opened',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "proposal_reminder" WA',
        status: 'success',
      },
    ],
    outcome: 'responded',
    triggeredAt: new Date('2024-12-13T22:00:00Z'),
  },
  {
    _id: 'rel_6',
    ruleId: 'rer_2',
    ruleName: 'No Response 5 Days — Escalate',
    leadId: 'l16',
    leadName: 'Ritu Saxena',
    trigger: 'no_response_5d',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "last_chance" WA',
        status: 'success',
      },
      { type: 'send_email', label: 'Send email', status: 'failed' },
      { type: 'assign_to_senior', label: 'Assign senior', status: 'pending' },
    ],
    outcome: 'no_response',
    triggeredAt: new Date('2024-12-13T16:00:00Z'),
  },
  {
    _id: 'rel_7',
    ruleId: 'rer_5',
    ruleName: 'Stage Stuck 7 Days — Intervene',
    leadId: 'l18',
    leadName: 'Swati Kapoor',
    trigger: 'stage_stuck',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "check_in" WA',
        status: 'success',
      },
      { type: 'schedule_call', label: 'Book call', status: 'success' },
      { type: 'assign_to_senior', label: 'Flag manager', status: 'success' },
    ],
    outcome: 'responded',
    triggeredAt: new Date('2024-12-10T14:00:00Z'),
  },
  {
    _id: 'rel_8',
    ruleId: 'rer_1',
    ruleName: 'Cold Lead — WhatsApp Re-engage',
    leadId: 'l18',
    leadName: 'Swati Kapoor',
    trigger: 'lead_cold',
    actionsExecuted: [
      {
        type: 'send_wa_template',
        label: 'Send "we_miss_you" WA',
        status: 'success',
      },
      { type: 'schedule_call', label: 'Schedule call', status: 'failed' },
    ],
    outcome: 'no_response',
    triggeredAt: new Date('2024-12-11T10:00:00Z'),
  },
];
