export const reEngagementRulesSeed = [
  {
    _id: 'rer_1',
    name: 'Cold Lead — WhatsApp Re-engage',
    trigger: 'lead_cold',
    triggerLabel: 'Lead goes cold (3+ days no contact)',
    conditions: { daysSinceContact: 3, temperature: 'cold' },
    actions: [
      {
        type: 'send_wa_template',
        label: 'Send "we_miss_you" WA template',
        templateName: 'we_miss_you',
        delay: 0,
        delayUnit: 'minutes',
      },
      {
        type: 'schedule_call',
        label: 'Schedule follow-up call in 24h',
        delay: 24,
        delayUnit: 'hours',
      },
    ],
    enabled: true,
    totalTriggered: 47,
    successRate: 34,
    lastTriggered: new Date('2024-12-14T08:00:00Z'),
    createdAt: '2024-11-01',
  },
  {
    _id: 'rer_2',
    name: 'No Response 5 Days — Escalate',
    trigger: 'no_response_5d',
    triggerLabel: 'No response for 5+ days',
    conditions: { daysSinceContact: 5 },
    actions: [
      {
        type: 'send_wa_template',
        label: 'Send "last_chance" WA template',
        templateName: 'last_chance',
        delay: 0,
        delayUnit: 'minutes',
      },
      {
        type: 'send_email',
        label: 'Send re-engagement email',
        delay: 2,
        delayUnit: 'hours',
      },
      {
        type: 'assign_to_senior',
        label: 'Assign to senior consultant',
        delay: 24,
        delayUnit: 'hours',
      },
    ],
    enabled: true,
    totalTriggered: 23,
    successRate: 22,
    lastTriggered: new Date('2024-12-14T07:00:00Z'),
    createdAt: '2024-11-05',
  },
  {
    _id: 'rer_3',
    name: 'No-Show — Auto Rebook',
    trigger: 'noshow',
    triggerLabel: 'Lead is a no-show on discovery call',
    conditions: {},
    actions: [
      {
        type: 'send_wa_template',
        label: 'Send "missed_call_rebook" WA template',
        templateName: 'missed_call_rebook',
        delay: 30,
        delayUnit: 'minutes',
      },
      {
        type: 'schedule_call',
        label: 'Auto-schedule new call in 48h',
        delay: 48,
        delayUnit: 'hours',
      },
    ],
    enabled: true,
    totalTriggered: 12,
    successRate: 58,
    lastTriggered: new Date('2024-12-12T09:30:00Z'),
    createdAt: '2024-11-10',
  },
  {
    _id: 'rer_4',
    name: 'Proposal Not Opened — Nudge',
    trigger: 'proposal_not_opened',
    triggerLabel: 'Proposal not opened within 48 hours',
    conditions: {},
    actions: [
      {
        type: 'send_wa_template',
        label: 'Send "proposal_reminder" WA template',
        templateName: 'proposal_reminder',
        delay: 0,
        delayUnit: 'minutes',
      },
    ],
    enabled: true,
    totalTriggered: 18,
    successRate: 72,
    lastTriggered: new Date('2024-12-13T22:00:00Z'),
    createdAt: '2024-11-12',
  },
  {
    _id: 'rer_5',
    name: 'Stage Stuck 7 Days — Intervene',
    trigger: 'stage_stuck',
    triggerLabel: 'Lead stuck in same stage for 7+ days',
    conditions: { daysSinceContact: 7, minScore: 30 },
    actions: [
      {
        type: 'send_wa_template',
        label: 'Send "check_in" WA template',
        templateName: 'check_in',
        delay: 0,
        delayUnit: 'minutes',
      },
      {
        type: 'schedule_call',
        label: 'Book personal call',
        delay: 4,
        delayUnit: 'hours',
      },
      {
        type: 'assign_to_senior',
        label: 'Flag for manager review',
        delay: 24,
        delayUnit: 'hours',
      },
    ],
    enabled: false,
    totalTriggered: 8,
    successRate: 38,
    lastTriggered: new Date('2024-12-10T14:00:00Z'),
    createdAt: '2024-11-20',
  },
  {
    _id: 'rer_6',
    name: 'SLA Breach — Immediate Action',
    trigger: 'sla_breach',
    triggerLabel: 'First response SLA breached (>2 hrs)',
    conditions: {},
    actions: [
      {
        type: 'send_wa_template',
        label: 'Send "quick_hello" WA template',
        templateName: 'quick_hello',
        delay: 0,
        delayUnit: 'minutes',
      },
      {
        type: 'assign_to_senior',
        label: 'Alert team lead',
        delay: 0,
        delayUnit: 'minutes',
      },
    ],
    enabled: true,
    totalTriggered: 31,
    successRate: 65,
    lastTriggered: new Date('2024-12-14T06:15:00Z'),
    createdAt: '2024-11-02',
  },
];
