import type { SalesAlert } from './sales-alerts.types';

// Copied from frontend mock data (`src/lib/salesMockData.ts`) so the UI keeps the same examples,
// but persistence now lives in MongoDB.
export const salesAlerts: Omit<SalesAlert, 'id'>[] = [
  {
    leadId: 'l5',
    leadName: 'Suresh Reddy',
    category: 'lead_cold',
    priority: 'critical',
    title: 'Lead Gone Cold',
    description:
      'No contact for 4 days. Suresh was in "Not Early" stage — high risk of permanent loss.',
    createdAt: '2024-12-14T08:00:00Z',
    dismissed: false,
    actionLabel: 'Send WhatsApp',
    actionType: 'send_wa',
  },
  {
    leadId: 'l10',
    leadName: 'Neha Gupta',
    category: 'lead_cold',
    priority: 'critical',
    title: 'Lead Gone Cold',
    description:
      'No contact for 5 days. Score 38 — Convert to Consulting stage. Needs immediate re-engagement.',
    createdAt: '2024-12-14T07:00:00Z',
    dismissed: false,
    actionLabel: 'Send WhatsApp',
    actionType: 'send_wa',
  },
  {
    leadId: 'l3',
    leadName: 'Rajesh Kumar',
    category: 'sla_breach',
    priority: 'critical',
    title: 'SLA Breach — First Response',
    description:
      'First response took 3 hrs (SLA: 2 hrs). Lead from Meta Ad — fast response critical for ad ROI.',
    createdAt: '2024-12-14T06:00:00Z',
    dismissed: false,
    actionLabel: 'View Lead',
    actionType: 'view_lead',
  },
  {
    leadId: 'l16',
    leadName: 'Ritu Saxena',
    category: 'stage_stuck',
    priority: 'warning',
    title: 'Stuck in Stage (10 days)',
    description:
      'Ritu has been in "Not Early" for 10 days. Average for this stage is 5 days. Pipeline is stalling.',
    createdAt: '2024-12-14T06:00:00Z',
    dismissed: false,
    actionLabel: 'Book Call',
    actionType: 'book_call',
  },
  {
    leadId: 'l5',
    leadName: 'Suresh Reddy',
    category: 'followup_overdue',
    priority: 'warning',
    title: 'Follow-up Overdue',
    description:
      'Last follow-up was 4 days ago. SLA requires contact every 3 days for nurture leads.',
    createdAt: '2024-12-14T05:00:00Z',
    dismissed: false,
    actionLabel: 'Send WhatsApp',
    actionType: 'send_wa',
  },
  {
    leadId: 'l8',
    leadName: 'Divya Menon',
    category: 'noshow_no_reengagement',
    priority: 'warning',
    title: 'No-Show — No Re-engagement',
    description:
      'Divya was a no-show on Dec 12. Follow-up sent but no response. Rebook or send personal WA.',
    createdAt: '2024-12-14T04:00:00Z',
    dismissed: false,
    actionLabel: 'Book Call',
    actionType: 'book_call',
  },
  {
    leadId: 'l10',
    leadName: 'Neha Gupta',
    category: 'followup_overdue',
    priority: 'warning',
    title: 'Follow-up Overdue',
    description:
      'No follow-up in 5 days. Neha is in Convert to Consulting — needs attention before she drops.',
    createdAt: '2024-12-14T03:00:00Z',
    dismissed: false,
    actionLabel: 'Add Note',
    actionType: 'add_note',
  },
  {
    leadId: 'l15',
    leadName: 'Deepak Choudhary',
    category: 'proposal_not_opened',
    priority: 'info',
    title: 'Proposal Not Opened (48h)',
    description:
      'Proposal sent 3 days ago, opened but not signed. Follow up to close.',
    createdAt: '2024-12-13T22:00:00Z',
    dismissed: false,
    actionLabel: 'Send WhatsApp',
    actionType: 'send_wa',
  },
  {
    leadId: 'l3',
    leadName: 'Rajesh Kumar',
    category: 'lead_going_cold',
    priority: 'info',
    title: 'Engagement Declining',
    description:
      'Response rate dropping. Last 2 messages had no reply. Consider a personal call.',
    createdAt: '2024-12-14T02:00:00Z',
    dismissed: false,
    actionLabel: 'Book Call',
    actionType: 'book_call',
  },
  {
    leadId: 'l18',
    leadName: 'Swati Kapoor',
    category: 'stage_stuck',
    priority: 'warning',
    title: 'Stuck in Stage (4 days)',
    description:
      'Swati in Gap Nurture for 4 days with declining engagement. Low commitment score.',
    createdAt: '2024-12-14T01:00:00Z',
    dismissed: false,
    actionLabel: 'Send WhatsApp',
    actionType: 'send_wa',
  },
  {
    leadId: 'l13',
    leadName: 'Sanjay Bhat',
    category: 'high_score_lead',
    priority: 'info',
    title: 'New Lead — Meta Ad',
    description:
      'New lead from "Gap Nurture Retargeting" campaign. Score: 22. Auto-enrolled in nurture sequence.',
    createdAt: '2024-12-14T10:30:00Z',
    dismissed: false,
    actionLabel: 'View Lead',
    actionType: 'view_lead',
  },
  {
    leadId: 'l11',
    leadName: 'Rohit Agarwal',
    category: 'high_score_lead',
    priority: 'info',
    title: 'Hot Lead — Discovery Booked',
    description:
      'Score 74, restaurant background, discovery call tomorrow. Prepare for high-value conversion.',
    createdAt: '2024-12-14T07:00:00Z',
    dismissed: true,
    actionLabel: 'View Lead',
    actionType: 'view_lead',
  },
];
